;
; THIS PART WRITTEN BY WRURXN
;
;
; THIS PART IS GENERATED BY PG_WRFPTB
;
EXPORTS _USRHPE@100                                                                     
EXPORTS _USRHPE=_USRHPE@100                                                             
